module.exports =
{
    "confirm": "Confirm",
    "cancel": "Cancel",
    "currentBudgetsHeadings": ["Budget", "Balance", "Rename/Delete", "Allocation ratio"],
    "recurringTransactionsHeadings": ["Name", "Amount", "Type", "Budget", "Category", "Next execution", "Interval", "End date", "Delete", "Edit"],
    "recurringTransactionsContent": ["earning", "spending", "days", "No recurring transactions available."],
    "addTransaction": "Add transaction",
    "transactionDialogTextElements": ["Here you can add new earnings or new spendings.", "Earning", "Spending", "Name", "Amount", "Category", "(optionally)", "Date", "Choose budget", "Allocate automatically", "Budget", "Automate", "End date", "never"],
    "intervalOptionsTextElements": ["weekly", "every 4 weeks", "monthly", "bimonthly", "quarterly", "biannual", "annual"],
    "addBudget": "Add budget",
    "budgetName": "Type in the name of the new budget.",
    "deleteBudget": "Delete budget",
    "reallyDelete": "Are you sure you want to delete this budget? <br> All the data will be lost.",
    "renameBudget": "Rename budget",
    "newBudgetName": "Type in a new name for this budget.",
    "autoAllocation": "Automated allocation",
    "allocationDialogTextElements": ["Here you can select how your earnings should be distributed.", "Activate automated allocation", "Distribute all earnings automatically to your budgets.", "Budget", "Percentage"],
    "displayTypes": ["Graph", "Table"],
    "mainContentTableHeadings": ["Date", "Name", "Amount", "Category", "Budget", "Type", "Delete"],
    "mainContentFilterText": ["All budgets", "All types", "Earnings", "Spendings", "All time", "to", "All transactions", "All categories"],
    "update": "Update",
    "earning": "Earning",
    "spending": "Spending",
    "apply": "Apply",
    "clear": "Clear",
    "rangeDatePickerPreset": ["Today", "Yesterday", "Last 7 days", "Last week (Mo-Su)", "Current month", "Previous month", "Current Year", "Last year", "All time"],
    "invalidInput": "Invalid input!",
    "noTransactions": "No transactions found!",
    "transferDialogTextElements": ["Here you can transfer money between your budgets.", "From", "To", "Amount"],
    "transfer": "Transfer money",
    "overallBalance": "Overall balance",
    "totalSum": "Total sum",
    "monthNames": [ "January","February","March","April","May","June", "July","August","September","October","November","December" ],
    "monthNamesShort": [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
	"dayNames": [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ],
	"dayNamesShort": [ "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" ],
	"dayNamesMin": [ "Su","Mo","Tu","We","Th","Fr","Sa" ],
    "editRecurringTransaction": ["Edit", "Amount", "Interval", "Update next execution"],
    "chooseMonthText": "For which month would you like to create an overview?",
    "chooseMonthTitle": "Choose a month",
    "reallyDeleteEntry": "Do you really want to delete this entry?",
	"reallyDeleteEntryTitle": "Delete entry",
	"chooseYearText": "For which year would you like to create an overview?",
	"chooseYearTitle": "Choose a year"
}
