module.exports =
{
    "recurringTransactionsHeadings": ["Name", "Amount", "Type", "Budget", "Category", "Next execution", "Interval", "End date", "Delete", "Edit"],
    "recurringTransactionsContent": ["earning", "spending", "days", "No recurring transactions available."],
    "reallyDelete": "Are you sure you want to delete this budget? <br> All the data will be lost.",
    "newBudgetName": "Type in a new name for this budget.",
    "displayTypes": ["Graph", "Table"],
    "mainContentTableHeadings": ["Date", "Name", "Amount", "Category", "Budget", "Type", "Delete"],
    "mainContentFilterText": ["All budgets", "All types", "Earnings", "Spendings", "All time", "to", "All transactions", "All categories"],
    "update": "Update",
    "apply": "Apply",
    "clear": "Clear",
    "rangeDatePickerPreset": ["Today", "Yesterday", "Last 7 days", "Last week (Mo-Su)", "Current month", "Previous month", "Current Year", "Last year", "All time"],
    "invalidInput": "Invalid input!",
    "noTransactions": "No transactions found!",
    "totalSum": "Total sum",
    "monthNames": [ "January","February","March","April","May","June", "July","August","September","October","November","December" ],
    "monthNamesShort": [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
	"dayNames": [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ],
	"dayNamesShort": [ "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" ],
	"dayNamesMin": [ "Su","Mo","Tu","We","Th","Fr","Sa" ],
    "editRecurringTransaction": ["Edit", "Amount", "Interval", "Update next execution"],
    "chooseMonthText": "For which month would you like to create an overview?",
    "chooseMonthTitle": "Choose a month",
    "reallyDeleteEntry": "Do you really want to delete this entry?",
	"reallyDeleteEntryTitle": "Delete entry",
	"chooseYearText": "For which year would you like to create an overview?",
	"chooseYearTitle": "Choose a year"
}
