module.exports = {
	'addBudget': 'Konto hinzuf\u00fcgen',
	'addTransaction': 'Eintrag hinzuf\u00fcgen',
	'allBudgets': 'Alle Konten',
	'allCategories': 'Alle Kategorien',
	'allocationRatio': 'Anteil bei Aufteilung',
	'allTimeSpending': 'Gesamtausgaben',
	'allTimeEarning': 'Gesamteinnahmen',
	'allTransactions': 'Alle Transaktionen',
	'allTypes': 'Alle Arten',
	'amount': 'Betrag',
	'autoAllocation': 'Automatische Aufteilung',
	'automate': 'Automatisieren',
	'balance': 'Kontostand',
	'balances': 'Bilanzen',
	'bar': 'Balkendiagramm',
	'budget': 'Konto',
	'cancel': 'Abbrechen',
	'category': 'Kategorie',
	'close': 'Schließen',
	'confirm': 'Best\u00e4tigen',
	'copy': 'Kopieren',
	'cut': 'Ausschneiden',
	'date': 'Datum',
	'dayNames': [
		'Sonntag',
		'Montag',
		'Dienstag',
		'Mittwoch',
		'Donnerstag',
		'Freitag',
		'Samstag'
	],
	'dayNamesMin': ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
	'dayNamesShort': ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
	'delete': 'L\u00f6schen',
	'deleteBudget': 'Konto l\u00f6schen',
	'doughnut': 'Ringdiagramm',
	'download': 'Herunterladen',
	'earning': 'Einnahme',	
	'edit': 'Bearbeiten',
	'endDate': 'Enddatum',
	'error': 'Fehler',
	'exit': 'Beenden',
	'help': 'Hilfe',
	'interval': 'Intervall',
	'intervalNames': [
		'w\u00f6chentlich',
		'alle 4 Wochen',
		'monatlich',
		'zweimonatlich',
		'viertelj\u00e4hrlich',
		'halbj\u00e4hrlich',
		'j\u00e4hrlich'
	],
	'later': 'Sp\u00e4ter',
	'line': 'Liniendiagramm',
	'minimize': 'Minimieren',
	'monthlySurplus': 'Monatlicher \u00dcberschuss',
	'monthNames': [
		'Januar',
		'Februar',
		'März',
		'April',
		'Mai',
		'Juni',
		'Juli',
		'August',
		'September',
		'Oktober',
		'November',
		'Dezember'
	],
    'monthNamesShort': [
		'Jan',
		'Feb',
		'Mär',
		'Apr',
		'Mai',
		'Jun',
		'Jul',
		'Aug',
		'Sep',
		'Okt',
		'Nov',
		'Dez'
	],
	'moveFileErr': 'Die Daten konnten nicht automatisch verschoben werden.',
	'name': 'Name',
	'never': 'nie',
	'nextExecution': 'N\u00e4chste Ausf\u00fchrung',
	'noEarning': 'Es gibt bisher keine Einnahmen!',
	'noSpending': 'Es gibt bisher keine Ausgaben!',
	'noRecurrTrans': 'Es sind keine wiederkehrenden Transaktionen vorhanden.',
	'noTransactions': 'Es wurden keine Transaktionen gefunden!',
	'overallBalance': 'Gesamtbilanz',
	'overview': '\u00dcberblick',
	'paste': 'Einfügen',
	'percentage': 'Anteil',
	'pie': 'Kreisdiagramm',
	'recentEarning': 'K\u00fcrzliche Einnahmen',
	'recentSpending': 'K\u00fcrzliche Ausgaben',
	'redo': 'Wiederholen',
	'reload': 'Neu laden',
	'renameBudget': 'Konto umbenennen',
	'renamedelete': 'Umbenennen/L\u00f6schen',
	'selUserText': 'Bitte w\u00e4hlen Sie einen Kontonamen aus. Es sind nur Buchstaben erlaubt.',
	'selUserTitle': 'Kontonamen ausw\u00e4hlen',
	'settings': 'Einstellungen',
	'spending': 'Ausgabe',
	'totalSum': 'Gesamtsumme',
	'transfer': 'Geld \u00fcbertragen',
	'type': 'Art',
	'updateAvailable': 'Update verf\u00fcgbar',
	'updateMessage': 'Es ist eine neue Version von FinanceList-Desktop verf\u00fcgbar!',
	'undo': 'Rückgängig',
	'window': 'Fenster',
	'windowSize': 'Fenstergr\u00f6\u00dfe',
	'zoomIn': 'Vergr\u00f6\u00dfern',
	'zoomOut': 'Verkleinern'
}