module.exports = {
	'addBudget': 'Add budget',
	'allocationRatio': 'Allocation ratio',
	'allTimeEarning': 'All time earnings',
	'allTimeSpending': 'All time spendings',
	'balance': 'Balance',
	'balances': 'Balances',
	'bar': 'Bar chart',
	'budget': 'Budget',
	'budgetName': 'Please type in the name of the new budget. The name must not be empty, it must not be longer than 30 characters and it must not exist yet.',
	'cancel': 'Cancel',
	'close': 'Close',
	'confirm': 'Confirm',
	'copy': 'Copy',
	'cut': 'Cut',
	'doughnut': 'Doughnut chart',
	'download': 'Download',
	'edit': 'Edit',
	'error': 'Error',
	'exit': 'Exit',
	'help': 'Help',
	'later': 'Later',
	'line': 'Line chart',
	'minimize': 'Minimize',
	'monthlySurplus': 'Monthly surplus',
	'moveFileErr': 'Failed to move your data automatically.',
	'noEarning': 'There are no earnings yet!',
	'noSpending': 'There are no spendings yet!',
	'overallBalance': 'Overall balance',
	'overview': 'Overview',
	'paste': 'Paste',
	'pie': 'Pie chart',
	'recentEarning': 'Recent earnings',
	'recentSpending': 'Recent spendings',
	'redo': 'Redo',
	'reload': 'Reload',
	'renamedelete': 'Rename/Delete',
	'selUserText': 'Please type in an account name. Only letters are allowed.',
	'selUserTitle': 'Select a account name',
	'settings': 'Settings',
	'totalSum': 'Total sum',
	'updateAvailable': 'Update available',
	'updateMessage': 'There is a new version of FinanceList-Desktop available!',
	'undo': 'Undo',
	'window': 'Window',
	'windowSize': 'Window size',
	'zoomIn': 'Zoom in',
	'zoomOut': 'Zoom out'
}