module.exports = {
	'addBudget': 'Konto hinzuf\u00fcgen',
	'addTransaction': 'Eintrag hinzuf\u00fcgen',
	'allocationRatio': 'Anteil bei Aufteilung',
	'allTimeSpending': 'Gesamtausgaben',
	'allTimeEarning': 'Gesamteinnahmen',
	'automate': 'Automatisieren',
	'balance': 'Kontostand',
	'balances': 'Bilanzen',
	'bar': 'Balkendiagramm',
	'budget': 'Konto',
	'cancel': 'Abbrechen',
	'close': 'Schließen',
	'confirm': 'Best\u00e4tigen',
	'copy': 'Kopieren',
	'cut': 'Ausschneiden',
	'doughnut': 'Ringdiagramm',
	'download': 'Herunterladen',
	'earning': 'Einnahme',	
	'edit': 'Bearbeiten',
	'endDate': 'Enddatum',
	'error': 'Fehler',
	'exit': 'Beenden',
	'help': 'Hilfe',
	'later': 'Sp\u00e4ter',
	'line': 'Liniendiagramm',
	'minimize': 'Minimieren',
	'monthlySurplus': 'Monatlicher \u00dcberschuss',
	'moveFileErr': 'Die Daten konnten nicht automatisch verschoben werden.',
	'never': 'nie',
	'noEarning': 'Es gibt bisher keine Einnahmen!',
	'noSpending': 'Es gibt bisher keine Ausgaben!',
	'overallBalance': 'Gesamtbilanz',
	'overview': '\u00dcberblick',
	'paste': 'Einfügen',
	'pie': 'Kreisdiagramm',
	'recentEarning': 'K\u00fcrzliche Einnahmen',
	'recentSpending': 'K\u00fcrzliche Ausgaben',
	'redo': 'Wiederholen',
	'reload': 'Neu laden',
	'renameBudget': 'Konto umbenennen',
	'renamedelete': 'Umbenennen/L\u00f6schen',
	'selUserText': 'Bitte w\u00e4hlen Sie einen Kontonamen aus. Es sind nur Buchstaben erlaubt.',
	'selUserTitle': 'Kontonamen ausw\u00e4hlen',
	'settings': 'Einstellungen',
	'spending': 'Ausgabe',
	'totalSum': 'Gesamtsumme',
	'updateAvailable': 'Update verf\u00fcgbar',
	'updateMessage': 'Es ist eine neue Version von FinanceList-Desktop verf\u00fcgbar!',
	'undo': 'Rückgängig',
	'window': 'Fenster',
	'windowSize': 'Fenstergr\u00f6\u00dfe',
	'zoomIn': 'Vergr\u00f6\u00dfern',
	'zoomOut': 'Verkleinern'
}