module.exports = {
	'addBudget': 'Add budget',
	'addTransaction': 'Add transaction',
	'allocationRatio': 'Allocation ratio',
	'allTimeEarning': 'All time earnings',
	'allTimeSpending': 'All time spendings',
	'amount': 'Amount',
	'autoAllocation': 'Automated allocation',
	'automate': 'Automate',
	'balance': 'Balance',
	'balances': 'Balances',
	'bar': 'Bar chart',
	'budget': 'Budget',
	'cancel': 'Cancel',
	'category': 'Category',
	'close': 'Close',
	'confirm': 'Confirm',
	'copy': 'Copy',
	'cut': 'Cut',
	'delete': 'Delete',
	'deleteBudget': 'Delete budget',
	'doughnut': 'Doughnut chart',
	'download': 'Download',
	'earning': 'Earning',
	'edit': 'Edit',
	'endDate': 'End date',
	'error': 'Error',
	'exit': 'Exit',
	'help': 'Help',
	'interval': 'Interval',
	'intervalNames': [
		'weekly',
		'every 4 weeks',
		'monthly',
		'bimonthly',
		'quarterly',
		'biannual',
		'annual'
	],
	'later': 'Later',
	'line': 'Line chart',
	'minimize': 'Minimize',
	'monthlySurplus': 'Monthly surplus',
	'moveFileErr': 'Failed to move your data automatically.',
	'name': 'Name',
	'never': 'never',
	'nextExecution': 'Next execution',
	'noEarning': 'There are no earnings yet!',
	'noSpending': 'There are no spendings yet!',
	'noRecurrTrans': 'There are no recurring transactions available.',
	'overallBalance': 'Overall balance',
	'overview': 'Overview',
	'paste': 'Paste',
	'percentage': 'Percentage',
	'pie': 'Pie chart',
	'recentEarning': 'Recent earnings',
	'recentSpending': 'Recent spendings',
	'redo': 'Redo',
	'reload': 'Reload',
	'renameBudget': 'Rename budget',
	'renamedelete': 'Rename/Delete',
	'selUserText': 'Please type in an account name. Only letters are allowed.',
	'selUserTitle': 'Select a account name',
	'settings': 'Settings',
	'spending': 'Spending',
	'totalSum': 'Total sum',
	'transfer': 'Transfer money',
	'type': 'Type',
	'updateAvailable': 'Update available',
	'updateMessage': 'There is a new version of FinanceList-Desktop available!',
	'undo': 'Undo',
	'window': 'Window',
	'windowSize': 'Window size',
	'zoomIn': 'Zoom in',
	'zoomOut': 'Zoom out'
}