module.exports = {
	'addBudget': 'Add Budget',
	'addTransaction': 'Add Transaction',
	'allBudgets': 'All Budgets',
	'allCategories': 'All Categories',
	'allocationRatio': 'Allocation Ratio',
	'allTimeEarning': 'All Time Earnings',
	'allTimeSpending': 'All Time Spendings',
	'allTransactions': 'All Transactions',
	'allTypes': 'All Types',
	'amount': 'Amount',
	'autoAllocation': 'Automated Allocation',
	'automate': 'Automate',
	'balance': 'Balance',
	'balances': 'Balances',
	'bar': 'Bar Chart',
	'budget': 'Budget',
	'cancel': 'Cancel',
	'category': 'Category',
	'close': 'Close',
	'confirm': 'Confirm',
	'copy': 'Copy',
	'cut': 'Cut',
	'date': 'Date',
	'dayNames': [
		'Sunday',
		'Monday',
		'Tuesday',
		'Wednesday',
		'Thursday',
		'Friday',
		'Saturday'
	],
	'dayNamesMin': ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
	'dayNamesShort': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
	'delete': 'Delete',
	'deleteBudget': 'Delete Budget',
	'doughnut': 'Doughnut Chart',
	'download': 'Download',
	'earning': 'Earning',
	'edit': 'Edit',
	'editBudget': 'Edit Budget',
	'editEntry': 'Edit Entry',
	'editRecTrans': 'Edit Recurring Transaction',
	'endDate': 'End Date',
	'error': 'Error',
	'exit': 'Exit',
	'help': 'Help',
	'interval': 'Interval',
	'intervalNames': [
		'Weekly',
		'Every 4 Weeks',
		'Monthly',
		'Bimonthly',
		'Quarterly',
		'Biannual',
		'Annual'
	],
	'invalidBudgetName': 'Invalid budget name. The budget name must not already be used; must contain only letters, digits and spaces and has a maximum length of %%MAXLEN%% characters.',
	'invalidCheckInput': 'The given input does not match the expected text.',
	'later': 'Later',
	'line': 'Line Chart',
	'minimize': 'Minimize',
	'monthNames': [
		'January',
		'February',
		'March',
		'April',
		'May',
		'June',
		'July',
		'August',
		'September',
		'October',
		'November',
		'December'
	],
    'monthNamesShort': [
		'Jan',
		'Feb',
		'Mar',
		'Apr',
		'May',
		'Jun',
		'Jul',
		'Aug',
		'Sep',
		'Oct',
		'Nov',
		'Dec'
	],
	'monthlySurplus': 'Monthly Surplus',
	'moveFileErr': 'Failed to move your data automatically.',
	'name': 'Name',
	'never': 'Never',
	'nextExecution': 'Next Execution',
	'noEarning': 'There are no earnings yet!',
	'noSpending': 'There are no spendings yet!',
	'noRecurrTrans': 'There are no recurring transactions available.',
	'noTransactions': 'No transactions found!',
	'overallBalance': 'Overall Balance',
	'overview': 'Overview',
	'paste': 'Paste',
	'percentage': 'Percentage',
	'pie': 'Pie Chart',
	'recentEarning': 'Recent Earnings',
	'recentSpending': 'Recent Spendings',
	'redo': 'Redo',
	'reload': 'Reload',
	'renameBudget': 'Rename Budget',
	'renamedelete': 'Rename/Delete',
	'selUserText': 'Please type in an account name. Only letters are allowed.',
	'selUserTitle': 'Select an Account Name',
	'settings': 'Settings',
	'spending': 'Spending',
	'sumUpTo100': 'The amounts must add up to 100\u0025.',
	'totalSum': 'Total Sum',
	'transfer': 'Transfer Money',
	'type': 'Type',
	'updateAvailable': 'Update Available',
	'updateMessage': 'There is a new version of FinanceList-Desktop available!',
	'undo': 'Undo',
	'window': 'Window',
	'windowSize': 'Window Size',
	'zoomIn': 'Zoom In',
	'zoomOut': 'Zoom Out'
}