module.exports = {
	'close': 'Schließen',
	'copy': 'Kopieren',
	'cross-device-err': 'Ger\u00e4te\u00fcbergreifendes Verschieben ist nicht m\u00f6glich.',
	'cut': 'Ausschneiden',
	'download': 'Herunterladen',
	'edit': 'Bearbeiten',
	'error': 'Fehler',
	'exit': 'Beenden',
	'later': 'Sp\u00e4ter',
	'minimize': 'Minimieren',
	'paste': 'Einfügen',
	'redo': 'Wiederholen',
	'reload': 'Neu laden',
	'totalSum': 'Gesamtsumme',
	'updateAvailable': 'Update verf\u00fcgbar',
	'updateMessage': 'Es ist eine neue Version von FinanceList-Desktop verf\u00fcgbar!',
	'undo': 'Rückgängig',
	'window': 'Fenster'
}