module.exports =
{
    "confirm": "Best\u00e4tigen",
    "cancel": "Abbrechen",
    "currentBudgetsHeadings": ["Konto", "Kontostand", "Umbenennen/L&ouml;schen", "Anteil bei Aufteilung"],
    "recurringTransactionsHeadings": ["Name", "Summe", "Art", "Konto", "Kategorie", "N&auml;chste Ausf&uuml;hrung", "Intervall", "Enddatum", "L&ouml;schen", "Bearbeiten"],
    "recurringTransactionsContent": ["Einnahme", "Ausgabe", "Tage", "Es sind keine wiederkehrenden Transaktionen vorhanden."],
    "addTransaction": "Eintrag hinzuf\u00fcgen",
    "transactionDialogTextElements": ["Hier k&ouml;nnen Sie neue Einnahmen oder Ausgaben hinzuf&uuml;gen.", "Einnahme", "Ausgabe", "Name", "Betrag", "Kategorie", "(optional)", "Datum", "Konto w&auml;hlen", "Automatisch verteilen", "Konto", "Automatisieren", "Enddatum", "nie"],
    "intervalOptionsTextElements": ["w&ouml;chentlich", "alle 4 Wochen", "monatlich", "zweimonatlich", "viertelj&auml;hrlich", "halbj&auml;hrlich", "j&auml;hrlich"],
    "addBudget": "Konto hinzuf\u00fcgen",
    "budgetName": "Geben Sie einen Namen f&uuml;r das neue Konto ein.",
    "deleteBudget": "Konto l\u00f6schen",
    "reallyDelete": "Wollen Sie dieses Konto wirklich l&ouml;schen? <br> Dann gehen alle gespeicherten Daten verloren.",
    "renameBudget": "Konto umbenennen",
    "newBudgetName": "Geben Sie einen neuen Namen f&uuml;r dieses Konto ein.",
    "autoAllocation": "Automatische Aufteilung",
    "allocationDialogTextElements": ["Hier k&ouml;nnen Sie ausw&auml;hlen, wie Ihre Einnahmen verteilt werden sollen.", "Automatische Verteilung aktivieren", "Verteilt alle Einnahmen automatisch auf mehrere Konten.", "Konto", "Anteil"],
    "displayTypes": ["Graph", "Tabelle"],
    "mainContentTableHeadings": ["Datum", "Name", "Summe", "Kategorie", "Konto", "Art", "L\u00f6schen"],
    "mainContentFilterText": ["Alle Konten", "Alle Arten", "Einnahmen", "Ausgaben", "Gesamter Zeitraum", "bis", "Alle Transaktionen", "Alle Kategorien"],
    "update": "Aktualisieren",
    "earning": "Einnahme",
    "spending": "Ausgabe",
    "apply": "Anwenden",
    "clear": "Zur\u00fccksetzen",
    "rangeDatePickerPreset": ["Heute", "Gestern", "Letzte 7 Tage", "Letzte Woche (Mo-So)", "Aktueller Monat", "Letzter Monat", "Aktuelles Jahr", "Letztes Jahr", "Gesamter Zeitraum"],
    "invalidInput": "Ung&uuml;ltige Eingabe!",
    "noTransactions": "Es wurden keine Transaktionen gefunden!",
    "transferDialogTextElements": ["Hier k&ouml;nnen Sie Geld zwischen Ihren Konten &uuml;bertragen.", "Von", "Nach", "Betrag"],
    "transfer": "Geld \u00fcbertragen",
    "overallBalance": "Gesamtbilanz",
    "totalSum": "Gesamtsumme",
    "monthNames": [ "Januar","Februar","März","April","Mai","Juni", "Juli","August","September","Oktober","November","Dezember" ],
    "monthNamesShort": [ "Jan","Feb","Mär","Apr","Mai","Jun", "Jul","Aug","Sep","Okt","Nov","Dez" ],
    "dayNames": [ "Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag" ],
	"dayNamesShort": [ "So","Mo","Di","Mi","Do","Fr","Sa" ],
	"dayNamesMin": [ "So","Mo","Di","Mi","Do","Fr","Sa" ],
    "editRecurringTransaction": ["Bearbeiten", "Summe", "Intervall", "N\u00e4chste Ausf\u00fchrung anpassen"],
    "chooseMonthText": "F\u00fcr welchen Monat soll eine \u00dcbersicht erstellt werden?",
    "chooseMonthTitle": "W\u00e4hlen Sie einen Monat aus",
    "reallyDeleteEntry": "Wollen Sie diesen Eintrag wirklich l\u00f6schen?",
	"reallyDeleteEntryTitle": "Eintrag l\u00f6schen",
	"chooseYearText": "F\u00fcr welches Jahr soll eine \u00dcbersicht erstellt werden?",
    "chooseYearTitle": "W\u00e4hlen Sie ein Jahr aus"
}
